// 所有集合名称常量，避免拼写错误
export const COLLECTIONS = {
  SETTINGS: 'settings',
  STAFF: 'staff',
  PRODUCTS: 'products',
  PROJECTS: 'projects',
  MEMBERS: 'members',
  MEMBER_PROJECTS: 'member_projects',
  INVENTORY: 'inventory',
  APPOINTMENTS: 'appointments',
  TRANSACTIONS: 'transactions',
  PUNCH_RECORDS: 'punch_records',
  ATTENDANCE_RECORDS: 'attendance_records',
  SHIFT_SCHEDULES: 'shift_schedules',
  SHIFT_ROTATIONS: 'shift_rotations',
  OPERATION_LOGS: 'operation_logs',
  POINTS_RECORDS: 'points_records',
  BALANCE_RECORDS: 'balance_records',
  NOTIFICATIONS: 'notifications',
  RECALL_TASKS: 'recall_tasks',
  GIFT_MATERIALS: 'gift_materials',
  GIFT_RECORDS: 'gift_records',
  CONSUMABLES: 'consumables',
}
